// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/tamagram/nesk/backend/ent/schema"
	"github.com/tamagram/nesk/backend/ent/task"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescTitle is the schema descriptor for title field.
	taskDescTitle := taskFields[0].Descriptor()
	// task.DefaultTitle holds the default value on creation for the title field.
	task.DefaultTitle = taskDescTitle.Default.(string)
	// taskDescDetails is the schema descriptor for details field.
	taskDescDetails := taskFields[1].Descriptor()
	// task.DefaultDetails holds the default value on creation for the details field.
	task.DefaultDetails = taskDescDetails.Default.(string)
}
