// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTask struct {
	Title   string `json:"title"`
	Details string `json:"details"`
}

type Task struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Details string `json:"details"`
}
